badge-server-url: http://badges.falsifiable.us
metadata:
  access_right: open
  license: CC-BY-4.0
  publication_type: article
  upload_type: publication
pipelines:
  sandy:
    envs:
      host:
        args: []
    parameters: []
    path: pipelines/sandy
    requirements: {}
    stages:
    - setup
    - run
    - validate
search_sources:
- popperized
version: 1
